import {
  ArrowRight,
  Award,
  BarChart3,
  BookOpen,
  CheckCircle2,
  ChevronRight,
  Diamond,
  Download,
  Edit3,
  Eye,
  Group,
  Hexagon,
  Home,
  LayoutDashboard,
  Link2,
  Lock,
  LogOut,
  Menu,
  MoonStar,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  Sparkles,
  Star,
  SunMedium,
  Trash2,
  Trophy,
  UserCircle2,
  Users,
  Wallet,
  X,
} from "lucide-react";

const icons = {
  account: UserCircle2,
  ambassador: Award,
  arrowRight: ArrowRight,
  barChart: BarChart3,
  book: BookOpen,
  chain: Link2,
  check: CheckCircle2,
  chevronRight: ChevronRight,
  dashboard: LayoutDashboard,
  defi: Wallet,
  diamond: Diamond,
  download: Download,
  edit: Edit3,
  eye: Eye,
  groups: Group,
  hexagon: Hexagon,
  home: Home,
  lock: Lock,
  logout: LogOut,
  menu: Menu,
  moon: MoonStar,
  plus: Plus,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  sun: SunMedium,
  trash: Trash2,
  trophy: Trophy,
  users: Users,
  wallet: Wallet,
  x: X,
};

export function Icon({ className = "size-5", name, strokeWidth = 2 }) {
  const Component = icons[name] || Sparkles;

  return <Component className={className} strokeWidth={strokeWidth} />;
}
